image: maven:3-jdk-11

stages:
  - test-dev02
  - main-stg02
  - test-sandbox
  - test-prod02

variables:
  TEST:
    description: Test type
  TAG:
    description: tag to run


before_script:
  - echo "********* $ENV ************"
  - echo "********* $MERGE_ENV ************"


sanity-test:
  stage: sanity-test

  script:
    - mvn clean verify -Dtags=$TAG
  after_script:
    - mvn allure:report
      - env="stg02"
      - test_type="Sanity"
      - echo "https://fabric2.gitlab.io/-/subscriptions/subscription-api-automation/-/jobs/${CI_JOB_ID}/artifacts/target/site/allure-maven-plugin/index.html"
      - sh report.sh ${CI_PROJECT_NAME} ${CI_JOB_ID} ${CI_PAGES_URL} ${env} ${service} ${test_type} ${CI_PIPELINE_URL}
  artifacts:
    when: always
    paths:
      - target/site
  only:
    variables:
      - $TEST == "manual"

test-dev02:
  stage: test-dev02
  script:
    - mvn clean verify -Dtags=@sanity -Denv=dev02
  only:
    variables:
      - $ENV == "develop"
      - $MERGE_ENV == "develop"
      - $ENV == "SUB-develop"

main-stg02:
  stage: main-stg02
  script:
    - mvn clean verify -Dtags=@sanity
  after_script:
    - mvn allure:report
    - env="stg02"
    - test_type="Sanity"
    - echo "https://fabric2.gitlab.io/-/subscriptions/subscription-api-automation/-/jobs/${CI_JOB_ID}/artifacts/target/site/allure-maven-plugin/index.html"
    - sh report.sh ${CI_PROJECT_NAME} ${CI_JOB_ID} ${CI_PAGES_URL} ${env} ${service} ${test_type} ${CI_PIPELINE_URL}
  artifacts:
    when: always
    paths:
      - target/site
  only:
    variables:
      - $ENV == "staging"
      - $MERGE_ENV == "staging"
      - $ENV == "SUB-staging"

test-sandbox:
  stage: test-sandbox
  script:
    - mvn clean verify -Dtags=@sanity -Denv=sandbox
  only:
    variables:
      - $ENV == "main"
      - $MERGE_ENV == "main"

test-prod02:
  stage: test-prod02
  script:
    - mvn clean verify -Dtags=@sanity -Denv=prod02
  only:
    variables:
      - $ENV == "main"
      - $MERGE_ENV == "main"



